Repository googleforgames/global-multiplayer-demo, pull requests merged in 2023-08, with the labels that each got.

#182 Updated waiting screen removal logic
  game/Content/MainGame/DS_GameModeBP.uasset
  game/Content/Player/DS_PlayerControllerBP.uasset
  game/Dockerfile
  infrastructure/schema/cloudbuild.yaml
Labels: bug

#185 Be explicit in the docs about which Unreal Version
  README.md
Labels: documentation, cleanup

#186 Update architecture diagram
  images/architecture.png
Labels: cleanup
