Repository googleforgames/global-multiplayer-demo, pull requests merged in 2024-05, with the labels that each got.

#258 Migrated service mesh for fleets to Terraform
  infrastructure/agones-gke.tf
  infrastructure/services-gke.tf
  platform/cloudbuild.yaml
Labels: cleanup

#260 Agones Installation to Cloud Deploy Params
  .gitignore
  infrastructure/agones-gke.tf
  infrastructure/files/agones/agones-install.yaml.tpl
  infrastructure/files/agones/skaffold.yaml.tpl
  infrastructure/pipelines.tf
  platform/agones/agones-system.yaml
  platform/agones/skaffold.yaml
Labels: enhancement

#262 Small fix for README.
  README.md
Labels: cleanup

#259 Add Cloud Deploy Automations
  README.md
  infrastructure/main.tf
  infrastructure/pipelines.tf
  infrastructure/terraform.tfvars.sample
  infrastructure/variables.tf
Labels: enhancement

#263 Add demos section to the README
  README.md
Labels: documentation
